import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";

const poppins = Poppins(
  {
    subsets: ["latin"],
    variable: "--font-poppins",
    display: "swap",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  }
)

const keepCalm = localFont({
  src: "./assets/fonts/keepcalm_medium.ttf",
  variable: "--font-keep-calm",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${poppins.variable} ${keepCalm.variable}  antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
